### ISSUE TITLE
В чем смысл умножения на 101?

### ISSUE THREAD

**Issue by phoenixweiss** [TommyHellANiggets/homework_4#1]
Поясните данный момент здесь в комментарии к данному Issue:
https://github.com/TommyHellANiggets/homework_4/blob/428bdb31e79cc7bdec4deaa539857ce9d205de2c/script.js#L6

В общем вероятность работает несколько иначе, но отклонение не существенное. Мне куда более интересно узнать что вы ответите чтобы принять решение зачитывать эту работу или нет.

**Comment by TommyHellANiggets** [comment]
Умножал на 101, т.к. в условиях был задан диапазон от 0 до 100, если бы я умножал на 100, диапазон был бы не полным, а именно от 0 до 99 
Понимаю, что на деле у меня диапазон 1-101 сдвинут на единицу, буду вспоминать и искать другие методы, чтобы можно было преобразовать внешне в 0-100.

**Comment by phoenixweiss** [comment]
Принимается.
